main:
    - name: CV
      title: Curriculum Vite
      pageRef: /cv
      weight: 20

    - name: CL
      title: Cover Letter
      pageRef: /cl
      weight:  30

footer:
    - name: Credits
      pageRef: /credits
      weight: 20

    - name:    Faq
      pageRef: /elephants
      weight:  20
