main:
    - name:    CV
      title:   Curriculum Vite
      pageRef: /cv
      weight:  20

    - name:    CL
      title:   Cover Letter
      pageRef: /cl
      weight:  30

    - name:    "↧"
      title:   Bottom
      pageRef: "#bot"
      weight:  30

footer:
    - name:    Credits
      title:   Credits
      pageRef: /credits
      weight:  30

    - name:    Faq
      title:   Frequently Asked Questions
      pageRef: /elephants
      weight:  20

    - name:    Changelog
      title:   Changelog
      pageRef: /log
      weight:  10

    - name:    "↥"
      title:   Top
      pageRef: "#top"
      weight:  100
