main:
    - name: ÖR
      title: Önéletrajz
      pageRef: /hu/cv
      weight: 20

    - name: ML
      title: Motivációs levél
      pageRef: /hu/cl
      weight:  30

footer:
    - name: Credits
      pageRef: /hu/credits
      weight: 20

    - name:    Gyik
      pageRef: /hu/elephants
      weight:  20
