baseURL = 'https://zelding.github.io/'
languageCode = 'en-us'
title = 'Kristof Dekany'
theme = 'ananke'
resourceDir = "../resources"
DefaultContentLanguage = "en"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = false
enableGitInfo = true

[markup.goldmark.parser]
    attribute = true

[languages]
    [languages.en]
        weight = 1
        contentDir = "content/en"
        languageName = "English"
    [languages.hu]
        title = "Dékány Kristóf"
        languageName = "Magyar"
        weight = 2
        contentDir = "content/hu"

[params]
    text_color = ""
    author = ""
    favicon = ""
    site_logo = ""
    description = "The last theme you'll ever need. Maybe."
    # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    background_color_class = "bg-black"
    recent_posts_number = 3
    body_classes = "ma0 dejavu bg-near-black"

[[params.ananke_socials]]
    name = "github"
    url = "https://github.com/zelding"

[[params.ananke_socials]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/users/4308297/zedling"

[[params.ananke_socials]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/kristof-dekany/"

[[params.ananke_socials]]
    name = "sourceforge"
    url = "https://sourceforge.net/u/zedling/profile/"

[[params.ananke_socials]]
    name = "youtube"
    url = "https://www.youtube.com/channel/UCccmWYLb5gCh1t5GeTDliNw"

[build]
    [[build.cacheBusters]]
        source = 'assets/.*\.(js|ts|jsx|tsx)'
        target = '(js|scripts|javascript)'
    [[build.cacheBusters]]
        source = 'assets/.*\.(.*)$'
        target = '$1'

[outputs]
    home    = ["HTML"]
    section = ["HTML", "RSS"]

[caches]
    [caches.images]
        dir    = ":cacheDir/images"
        maxAge = "1440h"
    [caches.assets]
        dir    = ":resourceDir/_gen"
        maxAge = -1
    [caches.getresource]
        dir = ":cacheDir/:project"
        maxage = '1h'

[services]
    [services.googleAnalytics]
        ID = 'G-40VRML108Z'
